/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buteco.view;

import buteco.enums.EStatus;
import buteco.model.produto.Categoria;
import buteco.model.produto.Grupo;
import buteco.model.produto.InsumosProduto;
import buteco.model.produto.Produto;
import buteco.service.CategoriaService;
import buteco.service.GrupoService;
import buteco.service.InsumosProdutoService;
import buteco.service.ProdutoService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author henrique
 */
//public ProdutoService produtoService;
//public CategoriaService categoriaService;
//public GrupoService grupoService;
//
//public ProdutoView(ProdutoService produtoService, CategoriaService categoriaService, GrupoService grupoService)
//{
//    this.produtoService = produtoService;
//    this.categoriaService = categoriaService;
//    this.grupoService = grupoService;
//    initComponents();
//    carregarDados();
//}
public class ProdutoView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdutoView.class.getName());

    /**
     * Creates new form ProdutoView
     */
    private ProdutoService produtoService;
    private CategoriaService categoriaService;
    private GrupoService grupoService;
    private List<Categoria> categorias;
    private List<Grupo> grupos;
    private InsumosProdutoService insumosProdutoService;
    private Produto produtoSelecionado;

//    private List<JTextField[]> linhasInsumo = new ArrayList<>();
    private List<Object[]> linhasInsumo = new ArrayList<>();

    public ProdutoView(ProdutoService produtoService, CategoriaService categoriaService, GrupoService grupoService, InsumosProdutoService insumosProdutoService) {
        this.insumosProdutoService = insumosProdutoService;
        this.produtoService = produtoService;
        this.categoriaService = categoriaService;
        this.grupoService = grupoService;
        initComponents();
        carregarDados();

        addMaisInsumos.setLayout(new BoxLayout(addMaisInsumos, BoxLayout.Y_AXIS));


        //listar selecao dos insumos ao apertar -----------------------------------------------------------------------
        tbProdutos.getSelectionModel().addListSelectionListener( e ->{
            if(!e.getValueIsAdjusting()){
                int linha = tbProdutos.getSelectedRow();
                if(linha >= 0){
                    Long id = (Long) tbProdutos.getValueAt(linha, 0);
                    produtoSelecionado = produtoService.findById(id);
                    carregarInsumos(id);
                    carregarInfoProduto(id);
                }
            }
        });
        // ----------------------------------------------------------------------------------------------------------

        //esconder/mostrar linha de insumos -------------------------------------------------------------------------
        ocultarCamposInsumos();
        selectCategoria.addActionListener( e -> {
            String select = (String) selectCategoria.getSelectedItem();
            if("PRODUTO COM INSUMOS".equals(select)){
                mostrarCamposInsumos();
            }else{
                ocultarCamposInsumos();
            }
        });

        // ----------------------------------------------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lbEstoque = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lbProduto = new javax.swing.JLabel();
        txtValorUnit = new javax.swing.JTextField();
        lbValUnit = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        lbGrupo = new javax.swing.JLabel();
        selectStatus = new javax.swing.JComboBox<>();
        lbInsumo = new javax.swing.JLabel();
        lbInsumoQtde = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        lbObs = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lbSubTituloProdutos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        lbSubTituloInsumos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbInsumos = new javax.swing.JTable();
        lbCategoria = new javax.swing.JLabel();
        selectCategoria = new javax.swing.JComboBox<>();
        selectGrupo = new javax.swing.JComboBox<>();
        btnAdcInsumos = new javax.swing.JButton();
        addMaisInsumos = new javax.swing.JPanel();
        txtInsumosQtde = new javax.swing.JTextField();
        selectInsumo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(28, 28, 30));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnVoltar.setDefaultCapable(false);
        btnVoltar.setRolloverEnabled(false);
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        lbEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        lbEstoque.setText("Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lbEstoque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 0));
        lbTitulo.setText("Cadastro de Produtos");

        txtProduto.setMaximumSize(new java.awt.Dimension(64, 24));
        txtProduto.addActionListener(this::txtProdutoActionPerformed);

        lbProduto.setBackground(new java.awt.Color(0, 0, 0));
        lbProduto.setForeground(new java.awt.Color(255, 255, 255));
        lbProduto.setText("Produto");

        txtValorUnit.addActionListener(this::txtValorUnitActionPerformed);

        lbValUnit.setBackground(new java.awt.Color(0, 0, 0));
        lbValUnit.setForeground(new java.awt.Color(255, 255, 255));
        lbValUnit.setText("Valor Uni.");

        lbStatus.setBackground(new java.awt.Color(0, 0, 0));
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText("Status");

        lbGrupo.setBackground(new java.awt.Color(0, 0, 0));
        lbGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lbGrupo.setText("Grupo");

        selectStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        selectStatus.setMaximumSize(new java.awt.Dimension(64, 24));
        selectStatus.setMinimumSize(new java.awt.Dimension(64, 24));
        selectStatus.setPreferredSize(new java.awt.Dimension(64, 24));
        selectStatus.addActionListener(this::selectStatusActionPerformed);

        lbInsumo.setBackground(new java.awt.Color(0, 0, 0));
        lbInsumo.setForeground(new java.awt.Color(255, 255, 255));
        lbInsumo.setText("Insumo");

        lbInsumoQtde.setBackground(new java.awt.Color(0, 0, 0));
        lbInsumoQtde.setForeground(new java.awt.Color(255, 255, 255));
        lbInsumoQtde.setText("Qtde");

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane2.setViewportView(txtObservacao);

        lbObs.setBackground(new java.awt.Color(0, 0, 0));
        lbObs.setForeground(new java.awt.Color(255, 255, 255));
        lbObs.setText("Observacao");

        btnAdicionar.setBackground(new java.awt.Color(51, 51, 51));
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 0));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setFocusable(false);
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnEditar.setForeground(new java.awt.Color(255, 255, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setFocusPainted(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        lbSubTituloProdutos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbSubTituloProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lbSubTituloProdutos.setText("Produtos");

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null},
                {"", null, null, null, null, null, null},
                {"", null, null, null, null, null, null},
                {"", null, null, null, null, null, null},
                {"", null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Valor Unit.", "Status", "Categoria", "Grupo", "Obs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbProdutos);

        lbSubTituloInsumos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbSubTituloInsumos.setForeground(new java.awt.Color(255, 255, 255));
        lbSubTituloInsumos.setText("Insumos");

        tbInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Produto", "Qtde Usada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbInsumos.setMinimumSize(new java.awt.Dimension(75, 180));
        tbInsumos.setPreferredSize(new java.awt.Dimension(375, 180));
        jScrollPane4.setViewportView(tbInsumos);

        lbCategoria.setBackground(new java.awt.Color(0, 0, 0));
        lbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbCategoria.setText("Categoria");

        selectCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "PRODUTO COM INSUMOS", "INSUMO", "SERVICO" }));

        selectGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BEBIDA", "SERVICO", "INGREDIENTE", "COMIDA", "INSUMO" }));

        btnAdcInsumos.setBackground(new java.awt.Color(51, 51, 51));
        btnAdcInsumos.setForeground(new java.awt.Color(255, 255, 0));
        btnAdcInsumos.setText("+");
        btnAdcInsumos.setBorderPainted(false);
        btnAdcInsumos.setFocusPainted(false);
        btnAdcInsumos.addActionListener(this::btnAdcInsumosActionPerformed);

        addMaisInsumos.setBackground(new java.awt.Color(28, 28, 30));

        javax.swing.GroupLayout addMaisInsumosLayout = new javax.swing.GroupLayout(addMaisInsumos);
        addMaisInsumos.setLayout(addMaisInsumosLayout);
        addMaisInsumosLayout.setHorizontalGroup(
            addMaisInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addMaisInsumosLayout.setVerticalGroup(
            addMaisInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        txtInsumosQtde.addActionListener(this::txtInsumosQtdeActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addMaisInsumos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbObs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lbInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectInsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbInsumoQtde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInsumosQtde)
                                .addGap(12, 12, 12)
                                .addComponent(btnAdcInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbSubTituloProdutos)
                                        .addGap(323, 323, 323))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(404, 404, 404)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbValUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtValorUnit))))
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSubTituloInsumos)
                .addGap(362, 362, 362))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbProduto)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbValUnit)
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGrupo)
                    .addComponent(lbCategoria)
                    .addComponent(lbStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdcInsumos)
                    .addComponent(txtInsumosQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbInsumo)
                    .addComponent(lbInsumoQtde)
                    .addComponent(selectInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaisInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSubTituloProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSubTituloInsumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ocultarCamposInsumos()
    {
        lbInsumo.setVisible(false);
        lbInsumoQtde.setVisible(false);
        txtInsumosQtde.setVisible(false);
        selectInsumo.setVisible(false);
        btnAdcInsumos.setVisible(false);
        addMaisInsumos.setVisible(false);
    }

    private void mostrarCamposInsumos()
    {
        lbInsumo.setVisible(true);
        selectInsumo.setVisible(true);
        lbInsumoQtde.setVisible(true);
        txtInsumosQtde.setVisible(true);
        btnAdcInsumos.setVisible(true);
        addMaisInsumos.setVisible(true);
    }

    private void carregarDados()
    {
        categorias = categoriaService.findAllCategoria();
        grupos = grupoService.findAllGrupo();

        selectCategoria.removeAllItems();
        for (Categoria c : categorias) selectCategoria.addItem(c.getCategoria());

        selectGrupo.removeAllItems();
        for (Grupo g : grupos) selectGrupo.addItem(g.getGrupo());

        DefaultTableModel model = (DefaultTableModel) tbProdutos.getModel();
        model.setRowCount(0); //zera a tabela

        List<Produto> produtos = produtoService.findAllProdutos();
        for(Produto p : produtos){
            model.addRow(new Object[]{
                    p.getId(),
                    p.getNome(),
                    p.getPrecoVenda(),
                    p.getStatus(),
                    p.getCategoria(),
                    p.getGrupo().getGrupo(),
                    p.getObservacao()
            });
        }
        carregarSelectInsumos();
    }

    private void carregarInfoProduto(Long id)
    {
        Produto produto = produtoService.findById(id);

        txtProduto.setText(produto.getNome());
        txtValorUnit.setText(Double.toString(produto.getPrecoVenda()));
        txtObservacao.setText(produto.getObservacao());

        //preenchendo os select
        selectStatus.setSelectedItem(produto.getStatus() == EStatus.ATIVO ? "Ativo" : "Inativo");
        selectCategoria.setSelectedItem(produto.getCategoria().getCategoria());
        selectGrupo.setSelectedItem(produto.getGrupo().getGrupo());

        if ("PRODUTO COM INSUMOS".equals(produto.getCategoria().getCategoria())) {
            JOptionPane.showMessageDialog(this, "Desculpa, campo de Insumos nao sao editaveis", "Campos Insumos", JOptionPane.INFORMATION_MESSAGE);
            ocultarCamposInsumos();
        }
    }

    private void carregarInsumos(Long id)
    {
        DefaultTableModel model = (DefaultTableModel) tbInsumos.getModel();
        model.setRowCount(0); //zera a tabela

        Produto produto = produtoService.findByIdComInsumos(id); // aqui

        for (InsumosProduto insumo : produto.getInsumos()) {
            model.addRow(new Object[]{
                    insumo.getId(),
                    insumo.getInsumo().getNome(),
                    insumo.getQtde()
            });
        }
    }

    private void carregarSelectInsumos() {
        selectInsumo.removeAllItems();
        produtoService.findAllProdutos().stream()
                .filter(p -> p.getGrupo().getGrupo().equals("INSUMO")
                        || p.getGrupo().getGrupo().equals("SERVICO") || p.getGrupo().getGrupo().equals("INGREDIENTE"))
                .forEach(p -> selectInsumo.addItem(p.getNome()));
    }

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void txtValorUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnitActionPerformed

    private void selectStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectStatusActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:

        List<String> errors = rules();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(this, String.join("\n", errors), "Campos Invalidos", JOptionPane.WARNING_MESSAGE);
            return; //trava para nao continuar
        }

        try {
            String nomeCategoria = (String) selectCategoria.getSelectedItem();
            Categoria categoria = categorias.stream()
                    .filter(c -> c.getCategoria().equals(nomeCategoria))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Categoria não encontrada"));

            String nomeGrupo = (String) selectGrupo.getSelectedItem();
            Grupo grupo = grupos.stream()
                    .filter(g -> g.getGrupo().equals(nomeGrupo))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Grupo não encontrado"));

            Produto produto = new Produto();
            produto.setNome(txtProduto.getText());
            produto.setPrecoVenda(Double.parseDouble(txtValorUnit.getText()));
            produto.setObservacao(txtObservacao.getText());
            produto.setStatus("Ativo".equals(selectStatus.getSelectedItem()) ? EStatus.ATIVO : EStatus.INATIVO); //tem que fazer isso, pois na hora que criei a tabela usei enum ;-;
            produto.setCategoria(categoria);
            produto.setGrupo(grupo);

            produtoService.salvarProduto(produto); //salva o produto
            if ("PRODUTO COM INSUMOS".equals(nomeCategoria)) { //caso for do tipo com insumo
                salvarInsumo(produto, (String) selectInsumo.getSelectedItem(), Double.parseDouble(txtInsumosQtde.getText())); //pega a info da linha fixa

                for (Object[] linha : linhasInsumo) {
                    JComboBox<String> combo = (JComboBox<String>) linha[0];
                    JTextField qtde = (JTextField) linha[1];
                    if (combo.getSelectedItem() != null) {
                        salvarInsumo(produto, (String) combo.getSelectedItem(), Double.parseDouble(qtde.getText()));
                    }
                }
            }
            //mesagem de sucesso
            JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos(); //limpa os campos
            carregarDados(); //carrega os dados da tabela novamente
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro ao salvar: "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }                                            

    private void salvarInsumo(Produto produto, String nomeInsumo, double qtde) {
        Produto insumo = produtoService.findAllProdutos().stream()
                .filter(p -> p.getNome().equalsIgnoreCase(nomeInsumo))
                .findFirst()
                .orElseThrow(() -> new RuntimeException("Insumo \"" + nomeInsumo + "\" não encontrado"));

        insumosProdutoService.salvarInsumo(new InsumosProduto(produto, insumo, qtde));
    }

    private void txtInsumosQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsumosQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsumosQtdeActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt)
    {
        if (produtoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela.", "Nenhum produto selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<String> errors = rules();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(this, String.join("\n", errors), "Campos Invalidos", JOptionPane.WARNING_MESSAGE);
            return; //trava para nao continuar
        }

        try {
            // Atualiza os campos no objeto já existente
            produtoSelecionado.setNome(txtProduto.getText().trim());
            produtoSelecionado.setPrecoVenda(Double.parseDouble(txtValorUnit.getText()));
            produtoSelecionado.setObservacao(txtObservacao.getText().trim());
            produtoSelecionado.setStatus("Ativo".equals(selectStatus.getSelectedItem()) ? EStatus.ATIVO : EStatus.INATIVO);

            String nomeCategoria = (String) selectCategoria.getSelectedItem();
            Categoria categoria = categorias.stream()
                    .filter(c -> c.getCategoria().equals(nomeCategoria))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Categoria não encontrada"));

            String nomeGrupo = (String) selectGrupo.getSelectedItem();
            Grupo grupo = grupos.stream()
                    .filter(g -> g.getGrupo().equals(nomeGrupo))
                    .findFirst()
                    .orElseThrow(() -> new RuntimeException("Grupo não encontrado"));

            produtoSelecionado.setCategoria(categoria);
            produtoSelecionado.setGrupo(grupo);

            produtoService.atualizarProduto(produtoSelecionado);

            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            produtoSelecionado = null;
            limparCampos();
            carregarDados();

        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnAdcInsumosActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
        JPanel linha = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 5));
        linha.setBackground(new java.awt.Color(28, 28, 30));

        JComboBox<String> comboInsumo = new JComboBox<>();
        produtoService.findAllProdutos().stream()
                .filter(p -> p.getGrupo().getGrupo().equals("INSUMO")
                        || p.getGrupo().getGrupo().equals("SERVICO")
                        || p.getGrupo().getGrupo().equals("INGREDIENTE"))
                .forEach(p -> comboInsumo.addItem(p.getNome()));

        JTextField campoQtde = new JTextField(8);

        JLabel lbI = new JLabel("Insumo:");
        JLabel lbQ = new JLabel("Qtde:");
        lbI.setForeground(java.awt.Color.WHITE);
        lbQ.setForeground(java.awt.Color.WHITE);

        linha.add(lbI);
        linha.add(comboInsumo);
        linha.add(lbQ);
        linha.add(campoQtde);

        linhasInsumo.add(new Object[]{comboInsumo, campoQtde});

        addMaisInsumos.add(linha);
        addMaisInsumos.revalidate();
        addMaisInsumos.repaint();
    }                                             

    private List<String> rules()
    {
        List<String> errors = new ArrayList<>();

        if(txtProduto.getText().isBlank()){
            errors.add("Nome do produto obrigatorio");
        }

        if (txtValorUnit.getText().isBlank()) {
            errors.add("Valor Unit obrigatorio");
        }else{
            try {
                double valor = Double.parseDouble(txtValorUnit.getText());
                if (valor <= 0) {
                    errors.add("Valor maior que zero");
                }
            } catch (NumberFormatException e) {
                errors.add("Valor Invalido!!!");
            }
        }

        //insumo so valida de selecionado
        if ("PRODUTO COM INSUMOS".equals(selectCategoria.getSelectedItem())) {

            //valdia os primeiros campos
            if (selectInsumo.getSelectedItem() == null) {
                errors.add("Informe ao menos um insumo.");
            }
            if (txtInsumosQtde.getText().isBlank()) {
                errors.add("Informe a quantidade do insumo.");
            } else { //mesma coisa do valor unitario
                try {
                    double qtde = Double.parseDouble(txtInsumosQtde.getText());
                    if (qtde <= 0) errors.add("Quantidade do insumo deve ser maior que zero.");
                } catch (NumberFormatException e) {
                    errors.add("Quantidade do insumo inválida.");
                }
            }

            // caso usado o btn de mais(+), ai percorre as linhas criadas e valida um por um
            for (int i = 0; i < linhasInsumo.size(); i++) {
                JComboBox<String> combo = (JComboBox<String>) linhasInsumo.get(i)[0];
                JTextField qtdeField = (JTextField) linhasInsumo.get(i)[1];
                String qtde = qtdeField.getText();
                int num = i + 2;

                if (combo.getSelectedItem() != null && qtde.isBlank()) {
                    errors.add("Linha " + num + ": quantidade não informada.");
                }
                if (!qtde.isBlank()) {
                    try {
                        double q = Double.parseDouble(qtde);
                        if (q <= 0) errors.add("Linha " + num + ": quantidade deve ser maior que zero.");
                    } catch (NumberFormatException e) {
                        errors.add("Linha " + num + ": quantidade inválida.");
                    }
                }
            }
        }

        return errors;
    }

    private void limparCampos()
    {
        txtProduto.setText("");
        txtValorUnit.setText("");
        txtObservacao.setText("");
        selectInsumo.setSelectedIndex(0);
        txtInsumosQtde.setText("");
        linhasInsumo.clear();
        addMaisInsumos.removeAll();
        addMaisInsumos.revalidate();
        addMaisInsumos.repaint();
//        ocultarCamposInsumo();
        selectCategoria.setSelectedIndex(0);
        selectGrupo.setSelectedIndex(0);
        selectStatus.setSelectedIndex(0);

    }
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new ProdutoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMaisInsumos;
    private javax.swing.JButton btnAdcInsumos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbEstoque;
    private javax.swing.JLabel lbGrupo;
    private javax.swing.JLabel lbInsumo;
    private javax.swing.JLabel lbInsumoQtde;
    private javax.swing.JLabel lbObs;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbSubTituloInsumos;
    private javax.swing.JLabel lbSubTituloProdutos;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValUnit;
    private javax.swing.JComboBox<String> selectCategoria;
    private javax.swing.JComboBox<String> selectGrupo;
    private javax.swing.JComboBox<String> selectInsumo;
    private javax.swing.JComboBox<String> selectStatus;
    private javax.swing.JTable tbInsumos;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextField txtInsumosQtde;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtValorUnit;
    // End of variables declaration//GEN-END:variables
}
