/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buteco.view.produto;

import buteco.controller.produtos.ProdutosControllerInterface;
import buteco.controller.produtos.dto.*;
import buteco.controller.produtos.dto.categoria.CategoriasResponse;
import buteco.controller.produtos.dto.grupo.GruposResponse;
import buteco.controller.produtos.impl.ProdutosControllerImpl;
import buteco.model.entity.produto.*;
import buteco.model.enums.EStatus;
import buteco.model.service.CategoriaService;
import buteco.model.service.GrupoService;
import buteco.model.service.InsumosProdutoService;
import buteco.model.service.ProdutoService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class ProdutoView extends javax.swing.JFrame {

    private EditProdutoResponse produtoResponseSelecionado;
    private EditProdutoResponse produtoResponse;
    private ProdutosControllerInterface produtoController;
    private List<CategoriasResponse> categoriaResponse;
    private List<GruposResponse> gruposResponse;

    private List<Object[]> linhasInsumo = new ArrayList<>();

    public ProdutoView(
            ProdutosControllerInterface produtoController
    ) {
        this.produtoController = produtoController;
        initComponents();
        carregarDados();

        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addMaisInsumos.setLayout(new BoxLayout(addMaisInsumos, BoxLayout.Y_AXIS));

        //listar selecao dos insumos ao apertar -----------------------------------------------------------------------
        tbProdutos.getSelectionModel().addListSelectionListener( e ->{
            if(!e.getValueIsAdjusting()){
                int linha = tbProdutos.getSelectedRow();
                if(linha >= 0){
                    Long id = (Long) tbProdutos.getValueAt(linha, 0);

                    produtoResponse = produtoController.findProduto(id);
                    produtoResponseSelecionado = produtoController.findProduto(id);
                    carregarInsumos(id);
                    carregarInfoProduto(produtoResponse);
                }
            }
        });
//        // ----------------------------------------------------------------------------------------------------------
//
//        //esconder/mostrar linha de insumos -------------------------------------------------------------------------
        btnAdcInsumos.setVisible(false);
        selectCategoria.addActionListener( e -> {
            try{ //usando o try apenas pois estava dando erro
                CategoriasResponse categoria = (CategoriasResponse) selectCategoria.getSelectedItem();
                if(!categoria.categoria().isEmpty()){
                    if("PRODUTO COM INSUMOS".equals(categoria.categoria())){
                        btnAdcInsumos.setVisible(true);
                    }else{
                        btnAdcInsumos.setVisible(false);
                    }

                }
            }catch (Exception eb){
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lbEstoque = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lbProduto = new javax.swing.JLabel();
        txtValorUnit = new javax.swing.JTextField();
        lbValUnit = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        lbGrupo = new javax.swing.JLabel();
        selectStatus = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        lbObs = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lbSubTituloProdutos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProdutos = new javax.swing.JTable();
        PainelInsumos = new javax.swing.JScrollPane();
        tbInsumos = new javax.swing.JTable();
        lbSubTituloInsumos = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        selectCategoria = new javax.swing.JComboBox<>();
        selectGrupo = new javax.swing.JComboBox<>();
        btnAdcInsumos = new javax.swing.JButton();
        addMaisInsumos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(28, 28, 30));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnVoltar.setDefaultCapable(false);
        btnVoltar.setRolloverEnabled(false);
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        lbEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        lbEstoque.setText("Estoque");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(lbEstoque))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 0));
        lbTitulo.setText("Cadastro de Produtos");

        txtProduto.setMaximumSize(new java.awt.Dimension(64, 24));

        lbProduto.setBackground(new java.awt.Color(0, 0, 0));
        lbProduto.setForeground(new java.awt.Color(255, 255, 255));
        lbProduto.setText("Produto");

        lbValUnit.setBackground(new java.awt.Color(0, 0, 0));
        lbValUnit.setForeground(new java.awt.Color(255, 255, 255));
        lbValUnit.setText("Valor Uni.");

        lbStatus.setBackground(new java.awt.Color(0, 0, 0));
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText("Status");

        lbGrupo.setBackground(new java.awt.Color(0, 0, 0));
        lbGrupo.setForeground(new java.awt.Color(255, 255, 255));
        lbGrupo.setText("Grupo");

        selectStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        selectStatus.setMaximumSize(new java.awt.Dimension(64, 24));
        selectStatus.setMinimumSize(new java.awt.Dimension(64, 24));
        selectStatus.setPreferredSize(new java.awt.Dimension(64, 24));

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane2.setViewportView(txtObservacao);

        lbObs.setBackground(new java.awt.Color(0, 0, 0));
        lbObs.setForeground(new java.awt.Color(255, 255, 255));
        lbObs.setText("Observacao");

        btnAdicionar.setBackground(new java.awt.Color(51, 51, 51));
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 0));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.setFocusable(false);
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        btnEditar.setBackground(new java.awt.Color(51, 51, 51));
        btnEditar.setForeground(new java.awt.Color(255, 255, 0));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setFocusPainted(false);
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        lbSubTituloProdutos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbSubTituloProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lbSubTituloProdutos.setText("Produtos");

        tbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Valor Unit.", "Status", "Categoria", "Grupo", "Obs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbProdutos);

        tbInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Qtde Usada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbInsumos.setMinimumSize(new java.awt.Dimension(75, 180));
        tbInsumos.setPreferredSize(new java.awt.Dimension(375, 180));
        PainelInsumos.setViewportView(tbInsumos);

        lbSubTituloInsumos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbSubTituloInsumos.setForeground(new java.awt.Color(255, 255, 255));
        lbSubTituloInsumos.setText("Insumos");

        lbCategoria.setBackground(new java.awt.Color(0, 0, 0));
        lbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lbCategoria.setText("Categoria");

        btnAdcInsumos.setBackground(new java.awt.Color(51, 51, 51));
        btnAdcInsumos.setForeground(new java.awt.Color(255, 255, 0));
        btnAdcInsumos.setText("+");
        btnAdcInsumos.setBorderPainted(false);
        btnAdcInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdcInsumos.setFocusPainted(false);
        btnAdcInsumos.addActionListener(this::btnAdcInsumosActionPerformed);

        addMaisInsumos.setBackground(new java.awt.Color(28, 28, 30));

        javax.swing.GroupLayout addMaisInsumosLayout = new javax.swing.GroupLayout(addMaisInsumos);
        addMaisInsumos.setLayout(addMaisInsumosLayout);
        addMaisInsumosLayout.setHorizontalGroup(
            addMaisInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addMaisInsumosLayout.setVerticalGroup(
            addMaisInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbObs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addMaisInsumos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(PainelInsumos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbValUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtValorUnit)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbSubTituloProdutos)
                                        .addGap(323, 323, 323))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(404, 404, 404)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSubTituloInsumos)
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdcInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(318, 318, 318))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbProduto)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbValUnit)
                        .addGap(30, 30, 30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGrupo)
                    .addComponent(lbCategoria)
                    .addComponent(lbStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAdcInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaisInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbObs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSubTituloProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSubTituloInsumos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Aqui ------------------------------------------------------------------
    private void carregarDados()
    {
        //pega do controler as response
        categoriaResponse = produtoController.listarCategorias();
        gruposResponse = produtoController.listarGrupos();

        //limpa o que tinha
        selectCategoria.removeAllItems();
        selectGrupo.removeAllItems();

        //carrega nos select as response
        for (CategoriasResponse c : categoriaResponse) selectCategoria.addItem(c);
        for(GruposResponse g : gruposResponse) selectGrupo.addItem(g);

        DefaultTableModel model = (DefaultTableModel) tbProdutos.getModel();
        model.setRowCount(0); //zera a tabela

        List<ProdutosResponse> produtos = produtoController.listarProdutos();
        for(ProdutosResponse p : produtos){
            model.addRow(new Object[]{
                p.id(),
                p.nome(),
                p.precoVenda(),
                p.status(),
                p.categoria(),
                p.grupo(),
                p.observacao()
            });
        }
        //esconde a tabela de insumos
        PainelInsumos.setVisible(false);
        lbSubTituloInsumos.setVisible(false);
    }

    private void carregarInfoProduto(EditProdutoResponse produto)
    {
        txtProduto.setText(produto.nome());
        txtValorUnit.setText(Double.toString(produto.preco_venda()));
        txtObservacao.setText(produto.obsevacao());

        //preenchendo os select
        selectStatus.setSelectedItem(produto.status().toString() == "ATIVO" ? "Ativo" : "Inativo");

        CategoriasResponse cat = produtoController.findCategoria(produto.fk_id_categoria());
        selectCategoria.setSelectedItem(cat);

        GruposResponse gp = produtoController.findGrupo(produto.fk_id_grupo());
        selectGrupo.setSelectedItem(gp);

//        if ("PRODUTO COM INSUMOS".equals(produtoEntity.getCategoria().getCategoria())) {
//            JOptionPane.showMessageDialog(this, "Desculpa, campo de Insumos nao sao editaveis", "Campos Insumos", JOptionPane.INFORMATION_MESSAGE);
//            ocultarCamposInsumos();
//        }
    }

    private void carregarInsumos(Long id)
    {
        DefaultTableModel model = (DefaultTableModel) tbInsumos.getModel();
        model.setRowCount(0); //zera a tabela

        if(produtoController.listarProdutosInsumos(id).isEmpty()){
            PainelInsumos.setVisible(false);
            lbSubTituloInsumos.setVisible(false);
        }else{
            PainelInsumos.setVisible(true);
            lbSubTituloInsumos.setVisible(true);
            produtoController.listarProdutosInsumos(id)
                .forEach(i -> model.addRow(new Object[]{
                        i.id(),
                        i.nome(),
                        i.qtde()
                }));

        }
    }

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:

        List<String> errors = rules();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(this, String.join("\n", errors), "Campos Invalidos", JOptionPane.WARNING_MESSAGE);
            return; //trava para nao continuar
        }

        try {
            CategoriasResponse categoria = (CategoriasResponse) selectCategoria.getSelectedItem();
            GruposResponse grupo = (GruposResponse) selectGrupo.getSelectedItem();

            ProdutoSelectResponse produto = produtoController.cadastrarProduto(
                txtProduto.getText(),
                Double.parseDouble(txtValorUnit.getText()),
                categoria.id(),
                grupo.id(),
                txtObservacao.getText()
            );

            //Caso tenha insumos
            if ("PRODUTO COM INSUMOS".equals(categoria.categoria())) {
                for (Object[] linha : linhasInsumo) {
                    JComboBox<String> combo = (JComboBox<String>) linha[0];
                    JTextField qtde = (JTextField) linha[1];
                    if (combo.getSelectedItem() != null) {
                        ProdutoSelectResponse insumo = (ProdutoSelectResponse) combo.getSelectedItem();
                        produtoController.cadastrarInsumo(produto.id(),Double.parseDouble(qtde.getText()), insumo.id());
                    }
                }
            }

            //mesagem de sucesso
            JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos(); //limpa os campos
            carregarDados(); //carrega os dados da tabela novamente
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro ao salvar: "+e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt)
    {
        if (produtoResponseSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um produto na tabela.", "Nenhum produto selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        List<String> errors = rules();
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(this, String.join("\n", errors), "Campos Invalidos", JOptionPane.WARNING_MESSAGE);
            return; //trava para nao continuar
        }

        try {
            CategoriasResponse categoria = (CategoriasResponse) selectCategoria.getSelectedItem();
            GruposResponse grupo = (GruposResponse) selectGrupo.getSelectedItem();

            produtoController.editarProduto(
                produtoResponseSelecionado.id(),
                txtProduto.getText().trim(),
                Double.parseDouble(txtValorUnit.getText()),
                selectStatus.getSelectedItem().toString(),
                categoria.id(),
                grupo.id(),
                txtObservacao.getText().trim()
            );

            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            produtoResponseSelecionado = null;
            limparCampos();
            carregarDados();

        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnAdcInsumosActionPerformed(java.awt.event.ActionEvent evt)
    {
        // TODO add your handling code here:
        JPanel linha = new JPanel(new GridBagLayout());
        linha.setBackground(new java.awt.Color(28, 28, 30));

        //obj de config que diz para o GridBagLayout() onde e cada componente deve ficar na "grade"
        GridBagConstraints gbc = new GridBagConstraints();
        //espacamento externo
        gbc.insets = new Insets(5, 6, 0, 6);
        //alinhamento a esquerda do painel
        gbc.anchor = GridBagConstraints.WEST;
        //preenche toda a largura horizontal do painel
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lbI = new JLabel("Insumo:");
        lbI.setForeground(java.awt.Color.WHITE);
        //gridx = coluna, gridy = linha, weightx = quanto espaco horizontal(0 nao estica, 1.0 estica para preencher)
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0;
        linha.add(lbI, gbc);

        JComboBox<ProdutoSelectResponse> comboInsumo = new JComboBox<>();
        gbc.gridx = 1; gbc.weightx = 1.0;
        produtoController.listarInsumos()
            .forEach(p ->
                    comboInsumo.addItem(produtoController.selectProduto(p.id(),p.nome()))
            );
        gbc.gridx = 1; gbc.weightx = 1.0;
        linha.add(comboInsumo, gbc);


        JLabel lbQ = new JLabel("Qtde:");
        lbQ.setForeground(java.awt.Color.WHITE);
        gbc.gridx = 2; gbc.weightx = 0;
        linha.add(lbQ, gbc);

        JTextField campoQtde = new JTextField(8);
        gbc.gridx = 3; gbc.weightx = 1.0;
        linha.add(campoQtde, gbc);

        JButton btnRemove = new JButton("-");
        //estilizacao copiada direto do que foi carregado no init do netBeans
        btnRemove.setBackground(new java.awt.Color(51, 51, 51));
        btnRemove.setForeground(new java.awt.Color(255, 255, 0));
        btnRemove.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnRemove.setBorderPainted(false);
        btnRemove.setFocusable(false);

        btnRemove.addActionListener(e->{
            addMaisInsumos.remove(linha);
            linhasInsumo.removeIf(obj -> obj[0] == comboInsumo);
            addMaisInsumos.revalidate();
            addMaisInsumos.repaint();
        });
        gbc.gridx = 4; gbc.weightx = 0;
        linha.add(btnRemove);

        linhasInsumo.add(new Object[]{comboInsumo, campoQtde});

        addMaisInsumos.add(linha);
        addMaisInsumos.revalidate();
        addMaisInsumos.repaint();
    }

    private List<String> rules()
    {
        List<String> errors = new ArrayList<>();

        if(txtProduto.getText().isBlank()){
            errors.add("Nome do produto obrigatorio");
        }

        if (txtValorUnit.getText().isBlank()) {
            errors.add("Valor Unit obrigatorio");
        }else{
            try {
                double valor = Double.parseDouble(txtValorUnit.getText());
                if (valor <= 0) {
                    errors.add("Valor maior que zero");
                }
            } catch (NumberFormatException e) {
                errors.add("Valor Invalido!!!");
            }
        }

        //insumo so valida de selecionado
        if ("PRODUTO COM INSUMOS".equals(selectCategoria.getSelectedItem())) {

            // caso usado o btn de mais(+), ai percorre as linhas criadas e valida um por um
            for (int i = 0; i < linhasInsumo.size(); i++) {
                JComboBox<String> combo = (JComboBox<String>) linhasInsumo.get(i)[0];
                JTextField qtdeField = (JTextField) linhasInsumo.get(i)[1];
                String qtde = qtdeField.getText();
                int num = i + 2;

                if (combo.getSelectedItem() != null && qtde.isBlank()) {
                    errors.add("Linha " + num + ": quantidade não informada.");
                }
                if (!qtde.isBlank()) {
                    try {
                        double q = Double.parseDouble(qtde);
                        if (q <= 0) errors.add("Linha " + num + ": quantidade deve ser maior que zero.");
                    } catch (NumberFormatException e) {
                        errors.add("Linha " + num + ": quantidade inválida.");
                    }
                }
            }
        }

        return errors;
    }

    private void limparCampos()
    {
        txtProduto.setText("");
        txtValorUnit.setText("");
        txtObservacao.setText("");
        linhasInsumo.clear();
        addMaisInsumos.removeAll();
        addMaisInsumos.revalidate();
        addMaisInsumos.repaint();
        selectCategoria.setSelectedIndex(0);
        selectGrupo.setSelectedIndex(0);
        selectStatus.setSelectedIndex(0);

    }

    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
////            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(() -> new ProdutoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PainelInsumos;
    private javax.swing.JPanel addMaisInsumos;
    private javax.swing.JButton btnAdcInsumos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbEstoque;
    private javax.swing.JLabel lbGrupo;
    private javax.swing.JLabel lbObs;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbSubTituloInsumos;
    private javax.swing.JLabel lbSubTituloProdutos;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValUnit;
    private javax.swing.JComboBox<CategoriasResponse> selectCategoria;
    private javax.swing.JComboBox<GruposResponse> selectGrupo;
    private javax.swing.JComboBox<String> selectStatus;
    private javax.swing.JTable tbInsumos;
    private javax.swing.JTable tbProdutos;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtValorUnit;
    // End of variables declaration//GEN-END:variables
}
